In [2]:
# 导入PyTorch核心库
import torch
# 导入神经网络模块（nn = Neural Network），包含所有预定义的层和损失函数
import torch.nn as nn
# 导入优化器模块，包含各种梯度下降算法
import torch.optim as optim
# 导入数据处理和加载工具
from torch.utils.data import DataLoader
# 导入计算机视觉相关的数据集和变换
from torchvision import datasets, transforms

# 导入numpy用于数据处理
import numpy as np
# 导入matplotlib用于可视化
import matplotlib.pyplot as plt

In [3]:
# 打印PyTorch版本
print(f"PyTorch版本: {torch.__version__}")

# 检查CUDA是否可用（CUDA是NVIDIA提供的GPU加速计算平台）
cuda_available = torch.cuda.is_available()
print(f"CUDA是否可用: {cuda_available}")

if cuda_available:
    # 打印GPU数量
    print(f"GPU数量: {torch.cuda.device_count()}")
    # 打印当前使用的GPU名称
    print(f"当前GPU: {torch.cuda.get_device_name(0)}")
    # 设置默认设备为GPU
    device = torch.device("cuda")
else:
    # 如果没有GPU，使用CPU
    device = torch.device("cpu")

print(f"使用的设备: {device}")

PyTorch版本: 2.9.1+cu130
CUDA是否可用: True
GPU数量: 1
当前GPU: NVIDIA GeForce RTX 4060 Laptop GPU
使用的设备: cuda


2.1 什么是张量（Tensor）
张量（Tensor） 是 PyTorch 中最基本的数据结构，可以理解为多维数组。它是神经网络中所有数据的载体，无论是输入数据、模型参数还是中间计算结果，都以张量的形式存在。
0 维张量：标量（单个数字）
1 维张量：向量（一维数组）
2 维张量：矩阵（二维数组）
3 维及以上张量：多维数组（例如 RGB 图像是 3 维张量：[高度，宽度，通道数]）

In [4]:
# 1. 从Python列表创建张量
tensor_from_list = torch.tensor([1, 2, 3, 4])
print("从列表创建的张量:", tensor_from_list)

# 2. 创建全0张量，参数是形状(shape)
zeros_tensor = torch.zeros((2, 3))  # 2行3列的全0矩阵
print("\n全0张量:\n", zeros_tensor)

# 3. 创建全1张量
ones_tensor = torch.ones((3, 2))  # 3行2列的全1矩阵
print("\n全1张量:\n", ones_tensor)

# 4. 创建指定范围内的连续整数张量
range_tensor = torch.arange(0, 10, 2)  # 从0到10（不包含10），步长为2
print("\n范围张量:", range_tensor)

# 5. 创建随机张量（值在0到1之间均匀分布）
rand_tensor = torch.rand((2, 2))
print("\n随机张量:\n", rand_tensor)

# 6. 创建随机--`-`张量（值服从标准正态分布，均值为0，方差为1）
randn_tensor = torch.randn((3, 3))
print("\n正态分布随机张量:\n", randn_tensor)

从列表创建的张量: tensor([1, 2, 3, 4])

全0张量:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

全1张量:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

范围张量: tensor([0, 2, 4, 6, 8])

随机张量:
 tensor([[0.7249, 0.6961],
        [0.8179, 0.5494]])

正态分布随机张量:
 tensor([[-1.5132, -0.0484, -0.0642],
        [-0.1245, -1.5617,  1.0801],
        [ 0.8097,  2.3061, -0.1226]])


In [5]:
# 创建一个示例张量
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

# 1. 查看张量的形状（shape）
print("张量形状:", x.shape)
print("张量形状（另一种写法）:", x.size())  # 与shape等价

# 2. 查看张量的维度数
print("张量维度数:", x.ndim)

# 3. 查看张量的数据类型（dtype）
print("张量数据类型:", x.dtype)

# 4. 转换张量的数据类型
x_int = x.to(torch.int32)
print("\n转换为int32后的张量:\n", x_int)
print("转换后的数据类型:", x_int.dtype)

张量形状: torch.Size([2, 3])
张量形状（另一种写法）: torch.Size([2, 3])
张量维度数: 2
张量数据类型: torch.float32

转换为int32后的张量:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
转换后的数据类型: torch.int32


In [9]:
# 创建两个示例张量
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# 1. 逐元素运算（element-wise）
print("逐元素加法:\n", a + b)
print("逐元素减法:\n", a - b)
print("逐元素乘法:\n", a * b)
print("逐元素除法:\n", a / b)

# 2. 矩阵乘法（这是神经网络中最重要的运算！）
# 线性层的核心就是矩阵乘法
matrix_mul = torch.matmul(a, b)
print("\n矩阵乘法结果:\n", matrix_mul)
# 简写形式
matrix_mul_short = a @ b
print("矩阵乘法简写结果:\n", matrix_mul_short)

# 3. 张量的聚合运算
print("\n张量所有元素的和:", a.sum())
print("张量所有元素的平均值:", a.mean())
print("张量的最大值:", a.max())
print("张量的最小值:", a.min())
print(a.sum(dim=0))
print(a.sum(dim=1))

逐元素加法:
 tensor([[ 6.,  8.],
        [10., 12.]])
逐元素减法:
 tensor([[-4., -4.],
        [-4., -4.]])
逐元素乘法:
 tensor([[ 5., 12.],
        [21., 32.]])
逐元素除法:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

矩阵乘法结果:
 tensor([[19., 22.],
        [43., 50.]])
矩阵乘法简写结果:
 tensor([[19., 22.],
        [43., 50.]])

张量所有元素的和: tensor(10.)
张量所有元素的平均值: tensor(2.5000)
张量的最大值: tensor(4.)
张量的最小值: tensor(1.)
tensor([4., 6.])
tensor([3., 7.])


In [11]:
# 创建一个示例张量
x = torch.arange(1, 13)  # 1维张量，包含1到12的整数
print("原始张量:", x)
print("原始形状:", x.shape)

# 1. reshape：改变张量的形状，元素总数不变
x_reshaped = x.reshape(3, 4)  # 变成3行4列的2维张量
print("\nreshape为(3,4):\n", x_reshaped)
print("reshape后的形状:", x_reshaped.shape)

# 2. transpose：交换两个维度
x_transposed = x_reshaped.transpose(0, 1)  # 交换第0维和第1维
print("\ntranspose后:\n", x_transposed)
print("transpose后的形状:", x_transposed.shape)

# 3. flatten：将多维张量展平为1维张量
# 这在卷积层连接到线性层时非常常用
x_flattened = x_reshaped.flatten()
print("\nflatten后:", x_flattened)
print("flatten后的形状:", x_flattened.shape)

# 4. unsqueeze：增加一个维度
x_unsqueezed = x.unsqueeze(0)  # 在第0维增加一个维度
print(x_unsqueezed)
print("\nunsqueeze后形状:", x_unsqueezed.shape)  # 从(12,)变成(1, 12)

原始张量: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
原始形状: torch.Size([12])

reshape为(3,4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
reshape后的形状: torch.Size([3, 4])

transpose后:
 tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])
transpose后的形状: torch.Size([4, 3])

flatten后: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
flatten后的形状: torch.Size([12])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

unsqueeze后形状: torch.Size([1, 12])


In [12]:
# 检查我们之前定义的device变量
print(f"当前使用的设备: {device}")

# 创建一个CPU上的张量
x_cpu = torch.tensor([1, 2, 3])
print("\n张量所在设备:", x_cpu.device)

# 1. 将张量移动到GPU
x_gpu = x_cpu.to(device)
print("移动到GPU后的设备:", x_gpu.device)

# 2. 直接在GPU上创建张量
x_gpu_direct = torch.tensor([4, 5, 6], device=device)
print("直接在GPU上创建的张量设备:", x_gpu_direct.device)

# 3. 将GPU上的张量移回CPU
x_cpu_back = x_gpu.cpu()
print("移回CPU后的设备:", x_cpu_back.device)

# 4. 重要：模型和数据必须在同一个设备上才能运算！
# 错误示例：CPU张量和GPU张量不能直接相加
try:
    result = x_cpu + x_gpu
except RuntimeError as e:
    print("\n错误示例（CPU和GPU张量相加）:", e)

# 正确示例：都移到同一个设备
result = x_cpu.to(device) + x_gpu
print("正确运算结果:", result)

当前使用的设备: cuda

张量所在设备: cpu
移动到GPU后的设备: cuda:0
直接在GPU上创建的张量设备: cuda:0
移回CPU后的设备: cpu

错误示例（CPU和GPU张量相加）: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
正确运算结果: tensor([2, 4, 6], device='cuda:0')


In [13]:
# 创建一个线性层：输入特征数为5，输出特征数为3
linear_layer = nn.Linear(in_features=5, out_features=3)

# 查看线性层的权重和偏置
print("权重矩阵形状:", linear_layer.weight.shape)  # [out_features, in_features]
print("偏置向量形状:", linear_layer.bias.shape)    # [out_features]

# 创建一个输入张量：批量大小为2，每个样本有5个特征
input_tensor = torch.randn(2, 5)
print("\n输入张量形状:", input_tensor.shape)

# 前向传播：将输入传入线性层
output_tensor = linear_layer(input_tensor)
print("输出张量形状:", output_tensor.shape)  # [2, 3]

权重矩阵形状: torch.Size([3, 5])
偏置向量形状: torch.Size([3])

输入张量形状: torch.Size([2, 5])
输出张量形状: torch.Size([2, 3])


In [14]:
# 创建ReLU激活函数
relu = nn.ReLU()

# 创建输入张量
x = torch.tensor([-2, -1, 0, 1, 2], dtype=torch.float32)
print("输入:", x)

# 应用ReLU
y = relu(x)
print("ReLU输出:", y)
# 创建Sigmoid激活函数
sigmoid = nn.Sigmoid()

# 应用Sigmoid
y = sigmoid(x)
print("Sigmoid输出:", y)
# 创建Softmax激活函数，dim=1表示在第1维上计算
softmax = nn.Softmax(dim=1)

# 创建输入张量：批量大小为2，3个类别
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("输入:\n", x)

# 应用Softmax
y = softmax(x)
print("Softmax输出:\n", y)
print("每行的和:", y.sum(dim=1))  # 每行的和都为1

输入: tensor([-2., -1.,  0.,  1.,  2.])
ReLU输出: tensor([0., 0., 0., 1., 2.])
Sigmoid输出: tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
输入:
 tensor([[1., 2., 3.],
        [4., 5., 6.]])
Softmax输出:
 tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])
每行的和: tensor([1., 1.])


In [17]:
x = torch.randn(2, 3, 4)
print(x)
# 沿dim=0求和 → 2个块合并为1个 → 形状(3, 4)
print(x.sum(dim=0))  # torch.Size([3, 4])

# 沿dim=1求和 → 每个块的3行合并为1行 → 形状(2, 4)
print(x.sum(dim=1))  # torch.Size([2, 4])

# 沿dim=2求和 → 每个块的4列合并为1列 → 形状(2, 3)
print(x.sum(dim=2))  # torch.Size([2, 3])


tensor([[[ 0.6755, -0.6488, -0.9105,  1.5218],
         [-1.0682, -0.7344,  1.9672,  0.2078],
         [-1.0788, -0.1579,  0.5844, -0.7815]],

        [[-1.4363, -0.9042, -0.7354,  0.6516],
         [-0.6964,  0.0689,  0.3945, -1.1023],
         [ 2.1045,  2.0426,  0.1538, -0.3714]]])
tensor([[-0.7608, -1.5530, -1.6459,  2.1734],
        [-1.7646, -0.6656,  2.3617, -0.8945],
        [ 1.0257,  1.8847,  0.7382, -1.1528]])
tensor([[-1.4716, -1.5411,  1.6411,  0.9481],
        [-0.0282,  1.2073, -0.1871, -0.8221]])
tensor([[ 0.6380,  0.3723, -1.4338],
        [-2.4243, -1.3353,  3.9295]])


In [18]:
# 创建交叉熵损失函数
cross_entropy_loss = nn.CrossEntropyLoss()

# 预测值：批量大小为2，3个类别（原始输出，没有经过Softmax）
predictions = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
# 真实标签：类别索引，不是one-hot编码
labels = torch.tensor([2, 0])

# 计算损失
loss = cross_entropy_loss(predictions, labels)
print("交叉熵损失:", loss.item())
# 创建均方误差损失函数
mse_loss = nn.MSELoss()

# 预测值和真实值
predictions = torch.tensor([1.0, 2.0, 3.0])
labels = torch.tensor([1.5, 2.5, 3.5])

# 计算损失
loss = mse_loss(predictions, labels)
print("均方误差损失:", loss.item())

交叉熵损失: 1.4076058864593506
均方误差损失: 0.25


In [19]:
# 创建一个简单的线性层作为模型
model = nn.Linear(5, 3)

# 创建SGD优化器
# lr是学习率，momentum是动量（可选，加速收敛）
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
# 创建Adam优化器
# lr是学习率，betas是动量参数（通常使用默认值）
optimizer = optim.Adam(model.parameters(), lr=0.001)